- attack-object:
    comments: ''
    id: T1552.007
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Container API
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1525
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Implant Internal Image
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1525
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Detect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Implant Internal Image
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1609
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Container Administration Command
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1610
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Deploy Container
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1613
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Significant
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Container and Resource Discovery
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1611
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Escape to Host
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1078
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Valid Accounts
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1078.001
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Default Accounts
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1078.004
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Configuration Management
      - Containers
      - Policy
    mapping-target: AnthosConfigManagement
    name: Cloud Accounts
    references:
    - 'https://cloud.google.com/anthos-config-management/ '
    tags:
    - Configuration Management
    - Containers
    - Policy
  metadata:
    attack-version: 10
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 04/27/2022
    last-update: ''
    mapping-platform: GCP
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
