- attack-object:
    comments: ''
    id: T1190
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Significant
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Exploit Public-Facing Application
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1189
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Significant
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Drive-by Compromise
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1203
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Significant
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Exploitation for Client Execution
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1059
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Protect
      score-value: Partial
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Command and Scripting Interpreter
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1090
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Protect
      score-value: Partial
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Proxy
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1595
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Protect
      score-value: Partial
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Active Scanning
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1046
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Network Service Scanning
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1071
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Protect
      score-value: Minimal
      tags:
      - Network
    mapping-target: AWS Web Application Firewall
    name: Application Layer Protocol
    references:
    - https://aws.amazon.com/waf/
    - https://docs.aws.amazon.com/waf/latest/developerguide/what-is-aws-waf.html
    - https://docs.aws.amazon.com/waf/latest/APIReference/Welcome.html
    - https://docs.aws.amazon.com/waf/latest/developerguide/aws-managed-rule-groups-list.html
    tags:
    - Network
  metadata:
    attack-version: 9
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 05/25/2021
    last-update: ''
    mapping-platform: AWS
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
