- attack-object:
    comments: ''
    id: T1595
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Protect
      score-value: Partial
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Active Scanning
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1190
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Significant
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Exploit Public-Facing Application
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1190
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Detect
      score-value: Significant
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Exploit Public-Facing Application
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1046
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Protect
      score-value: Partial
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Network Service Scanning
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1046
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Detect
      score-value: Partial
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Network Service Scanning
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1071
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Protect
      score-value: Minimal
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Application Layer Protocol
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1071
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Detect
      score-value: Minimal
      tags:
      - Azure Security Center Recommendation
    mapping-target: Azure Web Application Firewall
    name: Application Layer Protocol
    references:
    - https://docs.microsoft.com/en-us/azure/web-application-firewall/overview
    tags:
    - Azure Security Center Recommendation
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 02/18/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1.0
    organization: ''
    technology-domain: enterprise
