- attack-object:
    comments: ''
    id: T1204
    mapping-pattern: ''
    name: User Execution
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    related-score: true
    score-category: Detect
    score-comment: This control only provides detection for one of this technique's
      sub-techniques while not providing any detection capability for its other sub-technique,
      and therefore its coverage score is Partial, resulting in a Partial score.
    score-value: Partial
    secondary-property: ''
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
    value: Adaptive Application Controls
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: 03/25/2021
    mapping-type: scoring
    mapping-verision: 1
    organization: ''
    platform: Azure
    platform-version: ''
- attack-object:
    comments: ''
    id: T1036
    mapping-pattern: ''
    name: Masquerading
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    related-score: true
    score-category: Detect
    score-comment: This control provides detection for some of this technique's sub-techniques
      and procedure examples and therefore its coverage score is Partial, resulting
      in a Partial score. Its detection occurs once every twelve hours, so its temporal
      score is also Partial.
    score-value: Partial
    secondary-property: ''
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
    value: Adaptive Application Controls
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: 03/25/2021
    mapping-type: scoring
    mapping-verision: 1
    organization: ''
    platform: Azure
    platform-version: ''
- attack-object:
    comments: ''
    id: T1553
    mapping-pattern: ''
    name: Subvert Trust Controls
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    related-score: true
    score-category: Detect
    score-comment: This control only provides detection for one of this technique's
      sub-techniques while not providing any detection capability for the remaining
      sub-techniques, and therefore its coverage score is Minimal, resulting in a
      Minimal score.
    score-value: Minimal
    secondary-property: ''
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
    value: Adaptive Application Controls
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: 03/25/2021
    mapping-type: scoring
    mapping-verision: 1
    organization: ''
    platform: Azure
    platform-version: ''
- attack-object:
    comments: ''
    id: T1554
    mapping-pattern: ''
    name: Compromise Client Software Binary
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    related-score: false
    score-category: Detect
    score-comment: Once this control is activated, it generates alerts for any executable
      that is run and is not included in an allow list. While name and publisher-based
      allow lists may fail to detect malicious modifications to executable client
      binaries, hash-based rules will still detect untrusted executables. Events are
      calculated once every twelve hours, so its temporal score is Partial.
    score-value: Partial
    secondary-property: ''
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
    value: Adaptive Application Controls
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: 03/25/2021
    mapping-type: scoring
    mapping-verision: 1
    organization: ''
    platform: Azure
    platform-version: ''
