- attack-object:
    comments: ''
    id: T1204
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Detect
      score-value: Partial
      tags:
      - Azure Security Center
      - Azure Security Center Recommendation
      - Azure Defender for Servers
    mapping-target: Adaptive Application Controls
    name: User Execution
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1036
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Detect
      score-value: Partial
      tags:
      - Azure Security Center
      - Azure Security Center Recommendation
      - Azure Defender for Servers
    mapping-target: Adaptive Application Controls
    name: Masquerading
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1553
    mapping-description: ''
    mapping-platform:
      related-score: true
      score-category: Detect
      score-value: Minimal
      tags:
      - Azure Security Center
      - Azure Security Center Recommendation
      - Azure Defender for Servers
    mapping-target: Adaptive Application Controls
    name: Subvert Trust Controls
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
- attack-object:
    comments: ''
    id: T1554
    mapping-description: ''
    mapping-platform:
      related-score: false
      score-category: Detect
      score-value: Partial
      tags:
      - Azure Security Center
      - Azure Security Center Recommendation
      - Azure Defender for Servers
    mapping-target: Adaptive Application Controls
    name: Compromise Client Software Binary
    references:
    - https://docs.microsoft.com/en-us/azure/security-center/security-center-adaptive-application
    tags:
    - Azure Security Center
    - Azure Security Center Recommendation
    - Azure Defender for Servers
  metadata:
    attack-version: 8.2
    author: ''
    contact: ctid@mitre-engenuity.org
    creation-date: 03/25/2021
    last-update: ''
    mapping-platform: Azure
    mapping-platform-version: ''
    mapping-version: 1
    organization: ''
    technology-domain: enterprise
