name: 'Add Tags'
description: 'Add GitHub Tags to release.'
inputs:
  token:
    description: 'GitHub token for creating tags.'
    required: false
    default: ${{ github.token }}
  release-please-config:
    description: 'Path to the release-please configuration.'
    required: false
    default: './release-please-config.json'
  release-please-manifest:
    description: 'The path to the release-please manifest.'
    required: false
    default: './.release-please-manifest.json'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
